[build]
  command = "sudo apt-get install libpq-dev && rvm install 3.0.0 && rvm use 3.0.0 --default && source ~/.bashrc && bundle install && yarn install && bin/rails db:create && bin/rails db:migrate && RAILS_ENV=test bin/rails db:create db:migrate && bin/ember-cli -u"
